name: Java CI Pipeline

on:
   push:
      branches: [ dev ]
   pull_request:
      branches: [ dev ]

jobs:
   build_and_test:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout Code
           uses: actions/checkout@v4
         
         - name: Set up JDK 17
           uses: actions/setup-java@v4
           with:
              java-version: '17'
              distribution: 'temurin'
              cache: maven

         - name: Build with Maven
           run: mvn -B package --file pom.xml
